package com.smartstudy.db;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class DataBaseInitializer {

    private final Connection connection;

    public DataBaseInitializer(Connection connection) {
        this.connection = connection;
    }

    public void initializeDatabase() throws RuntimeException {
        try {
            connection.setAutoCommit(false);
            createUserTable();
            createStudentTable();
            createAdminTable();
            createLibraryTable();
            createTimePolicyTable();
            createStudyAreaTable();
            createSeatTable();
            createAccessSessionTable();
            createReservationTable();
            createTemporaryLeaveTable();
            createAbandonmentReportTable();
            connection.commit();

        } catch (SQLException e) {
            try {
                connection.rollback();
            } catch (SQLException rollbackException) {
                rollbackException.printStackTrace();
            }
            throw new RuntimeException("Errore durante l'inizializzazione del database", e);
        } finally {
            try {
                connection.setAutoCommit(true);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }


    private void createUserTable() throws SQLException {
        String sql = """
            CREATE TABLE IF NOT EXISTS app_user (
                user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(50) NOT NULL,
                surname VARCHAR(50) NOT NULL,
                email VARCHAR(100) NOT NULL UNIQUE
            )
        """;
        Statement statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

    private void createStudentTable() throws SQLException {
        String sql = """
            CREATE TABLE IF NOT EXISTS student (
                user_id INTEGER PRIMARY KEY,
                card_active BOOLEAN NOT NULL,

                CONSTRAINT fk_student_user
                    FOREIGN KEY (user_id)
                    REFERENCES app_user(user_id)
                    ON UPDATE CASCADE
                    ON DELETE CASCADE
            )
        """;
        Statement statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

    private void createAdminTable() throws SQLException {
        String sql = """
            CREATE TABLE IF NOT EXISTS admin (
                user_id INTEGER PRIMARY KEY,

                CONSTRAINT fk_admin_user
                    FOREIGN KEY (user_id)
                    REFERENCES app_user(user_id)
                    ON UPDATE CASCADE
                    ON DELETE CASCADE
            )
        """;
        Statement statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

    private void createLibraryTable() throws SQLException {
        String sql = """
            CREATE TABLE IF NOT EXISTS library (
                id_library INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                opening_time TIME NOT NULL,
                closing_time TIME NOT NULL,
                street VARCHAR(100) NOT NULL,
                number VARCHAR(20) NOT NULL,
                city VARCHAR(100) NOT NULL
            )
        """;
        Statement statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

    private void createTimePolicyTable() throws SQLException {
        String sql = """
            CREATE TABLE IF NOT EXISTS time_policy (
                id_policy INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                max_temporary_leave_min INTEGER NOT NULL,
                max_temporary_leave_times INTEGER NOT NULL,

                CONSTRAINT chk_time_policy_leave_min
                    CHECK (max_temporary_leave_min >= 0),

                CONSTRAINT chk_time_policy_leave_times
                    CHECK (max_temporary_leave_times >= 0)
            )
        """;
        Statement statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

    private void createStudyAreaTable() throws SQLException {
        String sql = """
            CREATE TABLE IF NOT EXISTS study_area (
                id_area INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                floor INTEGER NOT NULL,
                type VARCHAR(30) NOT NULL,
                id_library INTEGER NOT NULL,
                id_policy INTEGER NOT NULL,

                CONSTRAINT fk_study_area_library
                    FOREIGN KEY (id_library)
                    REFERENCES library(id_library)
                    ON UPDATE CASCADE
                    ON DELETE CASCADE,

                CONSTRAINT fk_study_area_policy
                    FOREIGN KEY (id_policy)
                    REFERENCES time_policy(id_policy)
                    ON UPDATE CASCADE
                    ON DELETE RESTRICT
            )
        """;
        Statement statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

    private void createSeatTable() throws SQLException {
        String sql = """
            CREATE TABLE IF NOT EXISTS seat (
                id_seat INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                qr_code VARCHAR(100) NOT NULL UNIQUE,
                type VARCHAR(30) NOT NULL,
                status VARCHAR(30) NOT NULL,
                id_area INTEGER NOT NULL,

                CONSTRAINT fk_seat_study_area
                    FOREIGN KEY (id_area)
                    REFERENCES study_area(id_area)
                    ON UPDATE CASCADE
                    ON DELETE CASCADE
            )
        """;
        Statement statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

    private void createAccessSessionTable() throws SQLException {
        String sql = """
            CREATE TABLE IF NOT EXISTS access_session (
                id_access INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                entry_time TIMESTAMP NOT NULL,
                exit_time TIMESTAMP,
                id_library INTEGER NOT NULL,
                user_id INTEGER NOT NULL,

                CONSTRAINT fk_access_session_library
                    FOREIGN KEY (id_library)
                    REFERENCES library(id_library)
                    ON UPDATE CASCADE
                    ON DELETE CASCADE,

                CONSTRAINT fk_access_session_student
                    FOREIGN KEY (user_id)
                    REFERENCES student(user_id)
                    ON UPDATE CASCADE
                    ON DELETE CASCADE,

                CONSTRAINT chk_access_session_time
                    CHECK (exit_time IS NULL OR exit_time >= entry_time)
            )
        """;
        Statement statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

    private void createReservationTable() throws SQLException {
        String sql = """
            CREATE TABLE IF NOT EXISTS reservation (
                id_reservation INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                start_time TIMESTAMP NOT NULL,
                end_time TIMESTAMP,
                status VARCHAR(30) NOT NULL,
                id_seat INTEGER NOT NULL,
                access_id INTEGER NOT NULL,

                CONSTRAINT fk_reservation_seat
                    FOREIGN KEY (id_seat)
                    REFERENCES seat(id_seat)
                    ON UPDATE CASCADE
                    ON DELETE RESTRICT,

                CONSTRAINT fk_reservation_access_session
                    FOREIGN KEY (access_id)
                    REFERENCES access_session(id_access)
                    ON UPDATE CASCADE
                    ON DELETE CASCADE,

                CONSTRAINT chk_reservation_time
                    CHECK (end_time IS NULL OR end_time > start_time)
            )
        """;

        Statement statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

    private void createTemporaryLeaveTable() throws SQLException {
        String sql = """
            CREATE TABLE IF NOT EXISTS temporary_leave (
                id_leave INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                start_time TIMESTAMP NOT NULL,
                expected_end_time TIMESTAMP NOT NULL,
                id_reservation INTEGER NOT NULL,

                CONSTRAINT fk_temporary_leave_reservation
                    FOREIGN KEY (id_reservation)
                    REFERENCES reservation(id_reservation)
                    ON UPDATE CASCADE
                    ON DELETE CASCADE,

                CONSTRAINT chk_temporary_leave_time
                    CHECK (expected_end_time > start_time)
            )
        """;

        Statement statement = connection.createStatement();
        statement.executeUpdate(sql);
    }

    private void createAbandonmentReportTable() throws SQLException {
        String sql = """
            CREATE TABLE IF NOT EXISTS abandonment_report (
                id_report INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMP NOT NULL,
                resolved_at TIMESTAMP,
                status VARCHAR(30) NOT NULL,
                description TEXT,
                id_reservation INTEGER NOT NULL,
                student_id INTEGER NOT NULL,
                admin_id INTEGER,

                CONSTRAINT fk_abandonment_report_reservation
                    FOREIGN KEY (id_reservation)
                    REFERENCES reservation(id_reservation)
                    ON UPDATE CASCADE
                    ON DELETE CASCADE,

                CONSTRAINT fk_abandonment_report_student
                    FOREIGN KEY (student_id)
                    REFERENCES student(user_id)
                    ON UPDATE CASCADE
                    ON DELETE CASCADE,

                CONSTRAINT fk_abandonment_report_admin
                    FOREIGN KEY (admin_id)
                    REFERENCES admin(user_id)
                    ON UPDATE CASCADE
                    ON DELETE SET NULL,

                CONSTRAINT chk_abandonment_report_time
                    CHECK (resolved_at IS NULL OR resolved_at >= created_at)
            )
        """;
        Statement statement = connection.createStatement();
        statement.executeUpdate(sql);
    }


    public void dropAllTables() {
        String sql = """
        DROP TABLE IF EXISTS
            abandonment_report,
            temporary_leave,
            reservation,
            access_session,
            seat,
            study_area,
            time_policy,
            admin,
            student,
            app_user,
            library
        CASCADE
    """;
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate(sql);
            System.out.println("Tutte le tabelle sono state eliminate correttamente.");
        } catch (SQLException e) {
            throw new RuntimeException("Errore durante l'eliminazione delle tabelle", e);
        }
    }

}