CREATE TABLE IF NOT EXISTS app_user
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50)  NOT NULL,
    password VARCHAR(100) NOT NULL,
    surname  VARCHAR(50)  NOT NULL,
    email    VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS student
(
    user_id     INTEGER PRIMARY KEY,
    card_active BOOLEAN NOT NULL,

    CONSTRAINT fk_student_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (user_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS library(
      id_library   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name         VARCHAR(100) NOT NULL,
      opening_time TIME         NOT NULL,
      closing_time TIME         NOT NULL,
      street       VARCHAR(100) NOT NULL,
      number       VARCHAR(20)  NOT NULL,
      city         VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS admin
(
    user_id    INTEGER PRIMARY KEY,
    is_present BOOLEAN NOT NULL DEFAULT FALSE,
    id_library INTEGER NOT NULL,
    CONSTRAINT fk_admin_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (user_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    CONSTRAINT fk_admin_library
        FOREIGN KEY (id_library)
            REFERENCES library (id_library)
            ON UPDATE CASCADE
            ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS time_policy
(
    id_policy                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_temporary_leave_min   INTEGER            NOT NULL,
    max_temporary_leave_times INTEGER            NOT NULL,
    name                      VARCHAR(50) UNIQUE NOT NULL,

    CONSTRAINT chk_time_policy_leave_min
        CHECK (max_temporary_leave_min >= 0),

    CONSTRAINT chk_time_policy_leave_times
        CHECK (max_temporary_leave_times >= 0)
);

CREATE TABLE IF NOT EXISTS study_area
(
    id_area    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    floor      INTEGER      NOT NULL,
    type       VARCHAR(30)  NOT NULL,
    id_library INTEGER      NOT NULL,
    id_policy  INTEGER      NOT NULL,

    CONSTRAINT fk_study_area_library
        FOREIGN KEY (id_library)
            REFERENCES library (id_library)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    CONSTRAINT fk_study_area_policy
        FOREIGN KEY (id_policy)
            REFERENCES time_policy (id_policy)
            ON UPDATE CASCADE
            ON DELETE RESTRICT,

    CONSTRAINT chk_valid_type CHECK (type IN ('STANDARD', 'GROUP', 'SILENT'))
);

CREATE TABLE IF NOT EXISTS seat
(
    id_seat INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qr_code VARCHAR(100) NOT NULL UNIQUE,
    type    VARCHAR(30)  NOT NULL,
    status  VARCHAR(30)  NOT NULL DEFAULT 'AVAILABLE',
    id_area INTEGER      NOT NULL,

    CONSTRAINT fk_seat_study_area
        FOREIGN KEY (id_area)
            REFERENCES study_area (id_area)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    CONSTRAINT chk_valid_type CHECK (type IN ('INDIVIDUAL', 'GROUP')),

    CONSTRAINT chk_valid_status CHECK (status IN ('AVAILABLE', 'UNAVAILABLE', 'BROKEN'))
);

CREATE TABLE IF NOT EXISTS access_session
(
    id_access  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_time TIMESTAMP NOT NULL,
    exit_time  TIMESTAMP,
    id_library INTEGER   NOT NULL,
    student_id INTEGER   NOT NULL,

    CONSTRAINT fk_access_session_library
        FOREIGN KEY (id_library)
            REFERENCES library (id_library)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    CONSTRAINT fk_access_session_student
        FOREIGN KEY (student_id)
            REFERENCES student (user_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    CONSTRAINT chk_access_session_time
        CHECK (exit_time IS NULL OR exit_time >= entry_time)
);

CREATE TABLE IF NOT EXISTS reservation
(
    id_reservation INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time     TIMESTAMP   NOT NULL,
    end_time       TIMESTAMP,
    status         VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    id_seat        INTEGER     NOT NULL,
    access_id      INTEGER     NOT NULL,

    CONSTRAINT fk_reservation_seat
        FOREIGN KEY (id_seat)
            REFERENCES seat (id_seat)
            ON UPDATE CASCADE
            ON DELETE RESTRICT,

    CONSTRAINT fk_reservation_access_session
        FOREIGN KEY (access_id)
            REFERENCES access_session (id_access)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    CONSTRAINT chk_reservation_time
        CHECK (end_time IS NULL OR end_time > start_time),

    CONSTRAINT chk_valid_status CHECK (status IN ('ACTIVE', 'TEMPORARILY_LEFT', 'CLOSED'))
);

CREATE TABLE IF NOT EXISTS temporary_leave
(
    id_leave          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time        TIMESTAMP NOT NULL,
    expected_end_time TIMESTAMP NOT NULL,
    id_reservation    INTEGER   NOT NULL,

    CONSTRAINT fk_temporary_leave_reservation
        FOREIGN KEY (id_reservation)
            REFERENCES reservation (id_reservation)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    CONSTRAINT chk_temporary_leave_time
        CHECK (expected_end_time > start_time)
);


CREATE TABLE IF NOT EXISTS abandonment_report
(
    id_report      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP   NOT NULL,
    resolved_at    TIMESTAMP,
    status         VARCHAR(30) NOT NULL DEFAULT 'OPENED',
    description    TEXT,
    id_reservation INTEGER     NOT NULL,
    student_id     INTEGER     NOT NULL,
    admin_id       INTEGER,

    CONSTRAINT fk_abandonment_report_reservation
        FOREIGN KEY (id_reservation)
            REFERENCES reservation (id_reservation)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    CONSTRAINT fk_abandonment_report_student
        FOREIGN KEY (student_id)
            REFERENCES student (user_id)
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    CONSTRAINT fk_abandonment_report_admin
        FOREIGN KEY (admin_id)
            REFERENCES admin (user_id)
            ON UPDATE CASCADE
            ON DELETE SET NULL,

    CONSTRAINT chk_abandonment_report_time
        CHECK (resolved_at IS NULL OR resolved_at >= created_at),

    CONSTRAINT chk_valid_status CHECK (status IN ('OPENED', 'PENDING', 'CONFIRMED', 'REJECTED', 'CLOSED'))
);